### ISSUE TITLE
parseOrder cannot handle BigNumber

### ISSUE THREAD

**Issue by Dex-C** [Uniswap/uniswapx-sdk#110]
for example, this transaction cannot be parsed by parseOrder, as the 18th value overflows:

https://etherscan.io/tx/0x190ecacc1d44b31df65fd9c9f2f4bc2ae78a884dd1b716a9c2042566b95b6edb

**Comment by ConjunctiveNormalForm** [comment]
can you try `DutchOrder.parse()` instead?

**Comment by Dex-C** [comment]
Gmgm, I tried DutchOrder.parse(), and it still gives an overflow error:

import { DutchOrder } from '@uniswap/uniswapx-sdk';

function processCalldata(calldata) {
    const chainId = 1; 
    const order = DutchOrder.parse(calldata, chainId);
    const orderData = order.info;

    return orderData;
}

export default processCalldata;


"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000064c21e330000000000000000000000000000000000000000000000000000000064c21e3300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec700000000000000000000000000000000000000000000000000000000000003e800000000000000000000000000000000000000000000000000000000000003e800000000000000000000000000000000000000000000000000000000000002000000000000000000000000006000da47483062a0d734ba3dc7576ce6a0b645c40000000000000000000000003c0c0d5e4ce41cf55a24d3fd740b6723ea201fdb000000000000000000000000000000000000000000000000000001899636cf03ffffffffffffffff6e5d2d49dbd61e236e98bdcba76f3b769800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc200000000000000000000000000000000000000000000000000005af3107a400000000000000000000000000000000000000000000000000000005af3107a40000000000000000000000000003c0c0d5e4ce41cf55a24d3fd740b6723ea201fdb"

**Comment by ConjunctiveNormalForm** [comment]
Please try with a more recent tx, the one you linked was from 177 days ago and the sdk has received many updates since then. Any tx from https://etherscan.io/address/0x6000da47483062a0d734ba3dc7576ce6a0b645c4 should work
