### ISSUE TITLE
Fix parseOrder function

### ISSUE THREAD

**Issue by rileydcampbell** [Uniswap/uniswapx-sdk#20]
The parseOrder function no longer works for the new contracts because we can no longer assume the location of the reactor address in the encoded order. 

See code [here](https://github.com/Uniswap/gouda-sdk/blob/ae91aede566eb72d9e8edb837f607c90f6ea1d63/src/order/index.ts#L16).

**Comment by hung-native** [comment]
I guess it's related to this issue? https://github.com/Uniswap/uniswapx-sdk/issues/79

May I ask what the fix is? Thanks!
